FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source (will be overwritten by volume mount)
COPY . .

EXPOSE 3001

# Default command (can be overridden)
CMD ["npm", "run", "dev"]
